### ISSUE TITLE
Dependency pyfasttext is no longer maintained

### ISSUE THREAD

**Issue by doug-friedman** [indix/whatthelang#10]
As an FYI, [pyfasttext is no longer maintained and the author recommends using the official Python bindings](https://github.com/vrasneur/pyfasttext).

I'm not sure if this is worth updating with a PR, but wanted to at least raise a potential issue.

**Comment by whiletruelearn** [comment]
@doug-friedman Thanks for reporting.  The latest binding of fasttext which facebook is developing is also not pushed to PyPi. This is is why we are still using `pyfasttext`. Also the model was trained a while back and the existing binding should work well with the model that is used. I have raised an [issue](https://github.com/facebookresearch/fastText/issues/708) anyways and we can think of migrating once we have something stable in PyPi.

**Comment by doug-friedman** [comment]
Ok no worries! Thanks for weighing in!

**Comment by doug-friedman** [comment]
As a follow-up, I'm attempting to see [how the existing pretrained model might work with the current Facebook python bindings for fasttext](https://github.com/doug-friedman/whatthelang/tree/facebook_compat). Using your test cases, I discovered a difference between the two bindings' results for your unknown test case string.

I was wondering if maybe you knew what might be causing this? I think it might be the threshold? If this is better filed under pyfasttext's issues, I'm happy to repost there.

```python
import whatthelang
import fastText

# Load wtl
wtl = whatthelang.WhatTheLang()

# pyfasttext model
pyft_model = wtl.model
facebook_model = fastText.load_model(wtl.model_file)

# Basic English Example
eng_test = ['English sentence']
print(pyft_model.predict(eng_test), pyft_model.predict_proba(eng_test))
print(facebook_model.predict(eng_test))
#[['en']] [[('en', 0.9158935522141515)]]
# ([['__label__en']], array([[0.88481706]]))

# Nonsense Example
bad_test = ['asdsf']
print(pyft_model.predict(bad_test), pyft_model.predict_proba(bad_test))
print(facebook_model.predict(bad_test))
#[[]] [[]]
#([['__label__en']], array([[0.12450418]]))
```

Thanks in advance!

**Comment by whiletruelearn** [comment]
Yes, I have seen this behavior before. For our usecase , the result from the older binding makes sense. 
Another thing to remember is that after model training, the fasttext codebase would have been still improved upon. Pyfasttext builds upon the snapshot of an older codebase and the new binding I presume would be built upon the latest codebase.

This is still a valid question and it might be a bug with the newer binding. IMO the right place to raise it  would be the Facebook repo .

**Comment by doug-friedman** [comment]
Will do. Thanks!
